// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ticcajzhhgisrfltrfed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpY2NhanpoaGdpc3JmbHRyZmVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTExMTcsImV4cCI6MjA2MDU2NzExN30.fbSfZufRhTSB_HjF9uzujrVtHgCru0Wfk6YonBHu-p8";

// Create the supabase client
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
